### PR TITLE
Fixed online castling uci representation

### LINKED ISSUE #26: Fix online castling uci representation
### What happened?

Exceptionally for online standard round castling is represented as king beat rook

### How can we reproduce the bug?

Make similar implementation to `_getMove` https://github.com/vovagorodok/mobile/commit/c7971f1a4cf4baaa8cddfab6d2dee4080695c7b2

### Expected behavior

Send castling representation as king move for standard round

### Device

N/A

### Operating system

N/A

### App version

latest

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vovagorodok**

### CODE REVIEW

File: src/externalDevice/bluetooth.ts [hunk 1]
```diff
@@ -154,7 +154,15 @@ export default {
     bluetoothConnection.lastMove = bluetoothConnection.centralState.lastMove
   },
   isRepeatedLastMove() {
-    return bluetoothConnection.lastMove === bluetoothConnection.centralState.lastMove
+    const last = bluetoothConnection.lastMove
+    const curr = bluetoothConnection.centralState.lastMove
+    if (!last || !curr) {
```
Comment (dkwach) [inline src/externalDevice/bluetooth.ts]: import isEqual from "lodash/isEqual";

isEqual(a, b); // true
?

**Review by dkwach — APPROVED** [review]

File: src/externalDevice/bluetooth.ts (hunk 1 above)
Comment (vovagorodok) [reply src/externalDevice/bluetooth.ts]: Done
